server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/contacts?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: test1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_schema: contacts
        jdbc:
          lob:
           non_contextual_creation: true

    generate-ddl: true

logging:
  level:
    com.progmasters: debug
    org.springframework.web: debug
    org.hibernate: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
